name: flutter_fractal
description: A Flutter package to create a Fractal Art with multiple drawing types such as Turtle Graphic, Mathematics. It will be useful for your awesome app.
version: 1.1.0
homepage: https://romanticdeveloper.com
repository: https://github.com/minhhung2556/romantic_project_flutter_fractal

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true